// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalog.API.Models;

#nullable disable

namespace MovieCatalog.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221102173529_edit_tokenEntitys")]
    partial class edit_tokenEntitys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.GenreEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieEntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieEntityId");

                    b.ToTable("GenreEntitys");
                });

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.MovieEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fees")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovieEntitys");
                });

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.ReviewEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("MovieId");

                    b.ToTable("ReviewEntitys");
                });

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserEntitys");
                });

            modelBuilder.Entity("MovieEntityUserEntity", b =>
                {
                    b.Property<string>("FavoriteMoviesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsersFavoriteId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoriteMoviesId", "UsersFavoriteId");

                    b.HasIndex("UsersFavoriteId");

                    b.ToTable("MovieEntityUserEntity");
                });

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.GenreEntity", b =>
                {
                    b.HasOne("MovieCatalog.API.Models.Entitys.MovieEntity", null)
                        .WithMany("Generes")
                        .HasForeignKey("MovieEntityId");
                });

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.ReviewEntity", b =>
                {
                    b.HasOne("MovieCatalog.API.Models.Entitys.UserEntity", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId");

                    b.HasOne("MovieCatalog.API.Models.Entitys.MovieEntity", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieEntityUserEntity", b =>
                {
                    b.HasOne("MovieCatalog.API.Models.Entitys.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("FavoriteMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalog.API.Models.Entitys.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersFavoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCatalog.API.Models.Entitys.MovieEntity", b =>
                {
                    b.Navigation("Generes");
                });
#pragma warning restore 612, 618
        }
    }
}
